#
# Copyright (c) 2021 Sung Ho Park and CSOS
#
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_DIR ?= ../app
CONFIG_NAME ?= arduino_adafruit_oled_featherwing_adafruitnrf52840e

include makefile.mk

